const API_PREFIX = import.meta.env.VITE_API_URL || '';

const ENDPOINTS = {
  AUTH: {
    LOGIN: `${API_PREFIX}/auth/login`,
    ME: `${API_PREFIX}/auth/me`,
    REFRESH: `${API_PREFIX}/auth/refresh`,
    LOGOUT: `${API_PREFIX}/auth/logout`,
  },
  LOCATIONS: {
    COUNTRIES: `${API_PREFIX}/locations/countries`,
    STATES: `${API_PREFIX}/locations/states`,
    CITIES: `${API_PREFIX}/locations/cities`,
  },
  INVITES: {
    LIST: `${API_PREFIX}/society-invites`,
    CREATE: `${API_PREFIX}/society-invites`,
    RESEND: (id) => `${API_PREFIX}/society-invites/${id}/resend`,
    BY_TOKEN: (token) => `${API_PREFIX}/society-invites/${token}`,
    ACCEPT: (token) => `${API_PREFIX}/society-invites/${token}/accept`,
  },
  SOCIETIES: {
    LIST: `${API_PREFIX}/societies`,
    GET: (id) => `${API_PREFIX}/societies/${id}`,
    UPDATE: (id) => `${API_PREFIX}/societies/${id}`,
    UPDATE_STATUS: (id) => `${API_PREFIX}/societies/${id}/status`,
    RESET_ADMIN_PASSWORD: (id) => `${API_PREFIX}/societies/${id}/admin-password`,
    MY_CONFIG: `${API_PREFIX}/societies/me/config`,
    UPDATE_CONFIG: `${API_PREFIX}/societies/me/config`,
  },
  BILLING: {
    LIST: `${API_PREFIX}/billing`,
    CREATE: `${API_PREFIX}/billing`,
    UPDATE_STATUS: (id) => `${API_PREFIX}/billing/${id}/status`,
    CREATE_ORDER: (id) => `${API_PREFIX}/billing/${id}/create-order`,
    VERIFY_PAYMENT: `${API_PREFIX}/billing/verify-payment`,
  },
  INVITE_ONBOARDING: {
    CREATE_SETUP_FEE_ORDER: (token) => `${API_PREFIX}/society-invites/${token}/create-setup-fee-order`,
    CREATE_SETUP_ORDER: (token) => `${API_PREFIX}/society-invites/${token}/create-setup-order`,
    VERIFY_PAYMENT: (token) => `${API_PREFIX}/society-invites/${token}/verify-payment`,
  },
  PAYMENTS: {
    OVERVIEW: `${API_PREFIX}/payments/overview`,
    MONTH_DETAIL: `${API_PREFIX}/payments/month-detail`,
    SEND_REMINDER: `${API_PREFIX}/payments/send-reminder`,
    CREATE_ORDER: `${API_PREFIX}/payments/create-order`,
    GENERATE_RECURRING: `${API_PREFIX}/payments/generate-recurring`,
  },
  PLANS: {
    LIST: `${API_PREFIX}/plans`,
    CREATE: `${API_PREFIX}/plans`,
    UPDATE: (id) => `${API_PREFIX}/plans/${id}`,
  },
  NOTIFICATIONS: {
    LIST: `${API_PREFIX}/notifications`,
    MARK_READ: (id) => `${API_PREFIX}/notifications/${id}/read`,
    MARK_ALL_READ: `${API_PREFIX}/notifications/mark-all-read`,
  },
  RESIDENTS: {
    LIST: `${API_PREFIX}/residents`,
    CREATE: `${API_PREFIX}/residents`,
    SET_PASSWORD: (id) => `${API_PREFIX}/residents/${id}/password`,
    DELETE: (id) => `${API_PREFIX}/residents/${id}`,
  },
  SIGNUP_REQUESTS: {
    LIST: `${API_PREFIX}/signup-requests`,
    REVIEW: (id) => `${API_PREFIX}/signup-requests/${id}`,
  },
  MEMBERS: {
    LIST: `${API_PREFIX}/members`,
    GET: (id) => `${API_PREFIX}/members/${id}`,
    CREATE: `${API_PREFIX}/members`,
    UPDATE: (id) => `${API_PREFIX}/members/${id}`,
    DELETE: (id) => `${API_PREFIX}/members/${id}`,
    FAMILY: (id) => `${API_PREFIX}/members/${id}/family`,
    FAMILY_UPDATE: (memberId, familyId) => `${API_PREFIX}/members/${memberId}/family/${familyId}`,
    FAMILY_DELETE: (memberId, familyId) => `${API_PREFIX}/members/${memberId}/family/${familyId}`,
    VEHICLES: (id) => `${API_PREFIX}/members/${id}/vehicles`,
    VEHICLE_UPDATE: (memberId, vehicleId) => `${API_PREFIX}/members/${memberId}/vehicles/${vehicleId}`,
    VEHICLE_DELETE: (memberId, vehicleId) => `${API_PREFIX}/members/${memberId}/vehicles/${vehicleId}`,
    DOCUMENTS: (id) => `${API_PREFIX}/members/${id}/documents`,
    DOCUMENT_DELETE: (memberId, docId) => `${API_PREFIX}/members/${memberId}/documents/${docId}`,
    EMERGENCY: (id) => `${API_PREFIX}/members/${id}/emergency`,
    EMERGENCY_UPDATE: (memberId, contactId) => `${API_PREFIX}/members/${memberId}/emergency/${contactId}`,
    EMERGENCY_DELETE: (memberId, contactId) => `${API_PREFIX}/members/${memberId}/emergency/${contactId}`,
    COMPLAINTS: (id) => `${API_PREFIX}/members/${id}/complaints`,
    MARKETPLACE: (id) => `${API_PREFIX}/members/${id}/marketplace`,
    ACTIVITY: (id) => `${API_PREFIX}/members/${id}/activity`,
  },
  FLATS: {
    LIST: `${API_PREFIX}/flats`,
    TOWERS: `${API_PREFIX}/flats/towers`,
    GET: (id) => `${API_PREFIX}/flats/${id}`,
    CREATE: `${API_PREFIX}/flats`,
    UPDATE: (id) => `${API_PREFIX}/flats/${id}`,
    BULK: `${API_PREFIX}/flats/bulk`,
    DELETE: (id) => `${API_PREFIX}/flats/${id}`,
    MEMBERS: (id) => `${API_PREFIX}/flats/${id}/members`,
    MEMBER_UPDATE: (flatId, memberId) => `${API_PREFIX}/flats/${flatId}/members/${memberId}`,
    MEMBER_DELETE: (flatId, memberId) => `${API_PREFIX}/flats/${flatId}/members/${memberId}`,
    VEHICLES: (id) => `${API_PREFIX}/flats/${id}/vehicles`,
    VEHICLE_UPDATE: (flatId, vehicleId) => `${API_PREFIX}/flats/${flatId}/vehicles/${vehicleId}`,
    VEHICLE_DELETE: (flatId, vehicleId) => `${API_PREFIX}/flats/${flatId}/vehicles/${vehicleId}`,
    DOCUMENTS: (id) => `${API_PREFIX}/flats/${id}/documents`,
    DOCUMENT_DELETE: (flatId, docId) => `${API_PREFIX}/flats/${flatId}/documents/${docId}`,
    COMPLAINTS: (id) => `${API_PREFIX}/flats/${id}/complaints`,
    BILLING: (id) => `${API_PREFIX}/flats/${id}/billing`,
  },
  GUARDS: {
    LIST: `${API_PREFIX}/guards`,
    GET: (id) => `${API_PREFIX}/guards/${id}`,
    CREATE: `${API_PREFIX}/guards`,
    UPDATE: (id) => `${API_PREFIX}/guards/${id}`,
    DELETE: (id) => `${API_PREFIX}/guards/${id}`,
    PROFILE_PICTURE: (id) => `${API_PREFIX}/guards/${id}/profile-picture`,
    SHIFTS: (guardId) => `${API_PREFIX}/guards/${guardId}/shifts`,
    SHIFT_UPDATE: (guardId, shiftId) => `${API_PREFIX}/guards/${guardId}/shifts/${shiftId}`,
    SHIFT_DELETE: (guardId, shiftId) => `${API_PREFIX}/guards/${guardId}/shifts/${shiftId}`,
    LEAVES: (guardId) => `${API_PREFIX}/guards/${guardId}/leaves`,
    LEAVES_ALL: `${API_PREFIX}/guards/leaves`,
    LEAVE_STATUS: (guardId, leaveId) => `${API_PREFIX}/guards/${guardId}/leaves/${leaveId}/status`,
    LEAVE_DELETE: (guardId, leaveId) => `${API_PREFIX}/guards/${guardId}/leaves/${leaveId}`,
    DOCUMENTS: (guardId) => `${API_PREFIX}/guards/${guardId}/documents`,
    DOCUMENT_DELETE: (guardId, docId) => `${API_PREFIX}/guards/${guardId}/documents/${docId}`,
  },
  VISITORS: {
    LIST: `${API_PREFIX}/visitors`,
    ENTRY: `${API_PREFIX}/visitors/entry`,
    EXIT: (id) => `${API_PREFIX}/visitors/${id}/exit`,
  },
  COMPLAINTS: {
    LIST: `${API_PREFIX}/complaints`,
    CREATE: `${API_PREFIX}/complaints`,
    UPDATE_STATUS: (id) => `${API_PREFIX}/complaints/${id}/status`,
  },
  NOTICES: {
    LIST: `${API_PREFIX}/notices`,
    CREATE: `${API_PREFIX}/notices`,
    DELETE: (id) => `${API_PREFIX}/notices/${id}`,
  },
  ADS: {
    LIST: `${API_PREFIX}/ads`,
    CREATE: `${API_PREFIX}/ads`,
    UPDATE: (id) => `${API_PREFIX}/ads/${id}`,
    DELETE: (id) => `${API_PREFIX}/ads/${id}`,
    UPLOAD_MEDIA: `${API_PREFIX}/ads/upload-media`,
  },
  VENDORS: {
    LIST: `${API_PREFIX}/vendors`,
    CREATE: `${API_PREFIX}/vendors`,
    UPDATE: (id) => `${API_PREFIX}/vendors/${id}`,
    DELETE: (id) => `${API_PREFIX}/vendors/${id}`,
  },
  DELIVERIES: {
    LIST: `${API_PREFIX}/deliveries`,
    CREATE: `${API_PREFIX}/deliveries`,
  },
  MARKETPLACE: {
    LIST: `${API_PREFIX}/marketplace`,
    LIST_GLOBAL: `${API_PREFIX}/marketplace/global`,
    GET: (id) => `${API_PREFIX}/marketplace/${id}`,
    CREATE: `${API_PREFIX}/marketplace`,
    UPDATE: (id) => `${API_PREFIX}/marketplace/${id}`,
    UPDATE_STATUS: (id) => `${API_PREFIX}/marketplace/${id}/status`,
    PIN: (id) => `${API_PREFIX}/marketplace/${id}/pin`,
    LISTED_GLOBALLY: (id) => `${API_PREFIX}/marketplace/${id}/listed-globally`,
    MEDIA: (id) => `${API_PREFIX}/marketplace/${id}/media`,
    DELETE: (id) => `${API_PREFIX}/marketplace/${id}`,
    TRANSACTIONS: `${API_PREFIX}/marketplace/transactions`,
  },
  ENGAGEMENT: {
    LOST_FOUND_LIST: `${API_PREFIX}/lost-found`,
    LOST_FOUND_CREATE: `${API_PREFIX}/lost-found`,
    LOST_FOUND_UPDATE_STATUS: (id) => `${API_PREFIX}/lost-found/${id}/status`,
    LOST_FOUND_DELETE: (id) => `${API_PREFIX}/lost-found/${id}`,
    POLLS_LIST: `${API_PREFIX}/polls`,
    POLLS_CREATE: `${API_PREFIX}/polls`,
    POLLS_DELETE: (id) => `${API_PREFIX}/polls/${id}`,
  },
  ANALYTICS: {
    DASHBOARD: `${API_PREFIX}/analytics/dashboard`,
  },
  CHAT: {
    GROUPS: `${API_PREFIX}/chat/groups`,
    GROUP: (id) => `${API_PREFIX}/chat/groups/${id}`,
    SOCIETY_USERS: `${API_PREFIX}/chat/groups/society-users`,
    MESSAGES: `${API_PREFIX}/chat/messages`,
    SEND_MESSAGE: `${API_PREFIX}/chat/message`,
    MESSAGE_READ: `${API_PREFIX}/chat/message/read`,
    MESSAGE_DELETE: (id) => `${API_PREFIX}/chat/message/${id}`,
    MESSAGE_PIN: (id) => `${API_PREFIX}/chat/message/${id}/pin`,
  },
};

export default ENDPOINTS;
